/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List checkins */
        get: {
            parameters: {
                query?: {
                    /** @description filter by course offering id */
                    offering_id?: number;
                    /** @description filter by schedule session id */
                    session_id?: number;
                    /** @description checkin status */
                    status?: "active" | "closed";
                    /** @description inclusive start YYYY-MM-DD */
                    from?: string;
                    /** @description inclusive end YYYY-MM-DD */
                    to?: string;
                    /** @description search by title */
                    q?: string;
                    /** @description 1-based page */
                    page?: number;
                    /** @description page size */
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description paged checkins */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.Paged"];
                    };
                };
                /** @description invalid status filter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a checkin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description checkin input */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["attendance.CheckinInput"];
                };
            };
            responses: {
                /** @description created checkin */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["attendance.CheckinView"];
                    };
                };
                /** @description invalid body / title required / session not in offering */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description offering or session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export offering attendance report as xlsx */
        get: {
            parameters: {
                query: {
                    /** @description course offering id */
                    offering_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description xlsx download */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                /** @description offering_id required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description offering not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's own checkins */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page */
                    page?: number;
                    /** @description page size */
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description paged my checkins */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.Paged"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan to check in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 6-digit scan code */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["attendance.ScanRequest"];
                };
            };
            responses: {
                /** @description scan result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["attendance.ScanResult"];
                    };
                };
                /** @description invalid code */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description code not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description closed or expired */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** L2 semester attendance summary */
        get: {
            parameters: {
                query: {
                    /** @description course offering id */
                    offering_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["attendance.OfferingSummary"];
                    };
                };
                /** @description offering_id required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description offering not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a checkin */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description checkin id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description checkin detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["attendance.CheckinView"];
                    };
                };
                /** @description invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a checkin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description checkin id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description closed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description already closed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a checkin's records as xlsx */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description checkin id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description xlsx download */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                /** @description invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/{id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a checkin's records */
        get: {
            parameters: {
                query?: {
                    /** @description record status */
                    status?: "present" | "late" | "absent" | "leave";
                    /** @description search by student name/no */
                    q?: string;
                    /** @description 1-based page */
                    page?: number;
                    /** @description page size */
                    page_size?: number;
                };
                header?: never;
                path: {
                    /** @description checkin id */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description paged records */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.Paged"];
                    };
                };
                /** @description invalid id/status */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description checkin not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkins/{id}/records/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Correct a student's record */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description checkin id */
                    id: number;
                    /** @description student user id */
                    userId: number;
                };
                cookie?: never;
            };
            /** @description new status */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["attendance.RecordUpdateInput"];
                };
            };
            responses: {
                /** @description updated record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["attendance.CheckinRecordView"];
                    };
                };
                /** @description invalid id/status */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description checkin/student not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "attendance.CheckinInput": {
            durationMinute?: number;
            lateMinutes?: number;
            offeringId?: number;
            sessionId?: number;
            title?: string;
        };
        "attendance.CheckinRecordView": {
            /** @description "grade name", "" when unknown */
            adminClass?: string;
            checkedAt?: string;
            checkinId?: number;
            displayName?: string;
            inRoster?: boolean;
            modifiedAt?: string;
            status?: string;
            studentNo?: string;
            userId?: number;
        };
        "attendance.CheckinView": {
            closedAt?: string;
            code?: string;
            counts?: components["schemas"]["attendance.Counts"];
            courseName?: string;
            createdAt?: string;
            createdBy?: number;
            expiresAt?: string;
            id?: number;
            lateMinutes?: number;
            offeringId?: number;
            semester?: string;
            sessionId?: number;
            sessionText?: string;
            startsAt?: string;
            /** @description active | closed */
            status?: string;
            teacher?: string;
            teachingClassName?: string;
            title?: string;
        };
        "attendance.Counts": {
            absent?: number;
            expected?: number;
            late?: number;
            leave?: number;
            present?: number;
        };
        "attendance.OfferingSummary": {
            checkins?: components["schemas"]["attendance.CheckinView"][];
            courseName?: string;
            offeringId?: number;
            rows?: components["schemas"]["attendance.SummaryRow"][];
            semester?: string;
            teacher?: string;
            teachingClassName?: string;
        };
        "attendance.RecordUpdateInput": {
            /** @example present */
            status?: string;
        };
        "attendance.ScanRequest": {
            /** @example 123456 */
            code?: string;
        };
        "attendance.ScanResult": {
            checkinId?: number;
            inRoster?: boolean;
            isNew?: boolean;
            status?: string;
            title?: string;
        };
        "attendance.SummaryRow": {
            adminClass?: string;
            displayName?: string;
            inRoster?: boolean;
            records?: {
                [key: string]: string;
            };
            studentNo?: string;
            totals?: {
                [key: string]: number;
            };
            userId?: number;
        };
        "httpx.ErrorResponse": {
            /** @example invalid request body */
            error?: string;
        };
        "httpx.Paged": {
            items?: unknown;
            page?: number;
            pageSize?: number;
            total?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
