services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: ocm-backend-prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: ocm-web-prod
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
