services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ocm-backend-prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
