services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ocm-web-prod
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
